### ISSUE TITLE
Rendering array of vnodes

### ISSUE THREAD

**Issue by luwes** [yelouafi/petit-dom#1]
Thanks for this great work! Is this the [fastest virtual dom](https://rawgit.com/krausest/js-framework-benchmark/master/webdriver-ts-results/table.html) on the web? :)

Is there an easy way to render an array of vnodes straight to `document.body` for example?
Or does this require separate mounting of each element?

**Comment by yelouafi** [comment]
>Is this the fastest virtual dom on the web? :)

This is kinda not trivial to quantify. see https://github.com/facebook/react/issues/10703 for more insights.

>Is there an easy way to render an array of vnodes straight to document.body for example?

this is not actually supported (You can always wrap them in a h('div',..) of course but direct support of arrays can have other uses as mentioned in https://github.com/facebook/react/issues/2127#issuecomment-90171492). 

But I'm thinking of adding this eventually.

**Comment by leeoniya** [comment]
i find it surprising how out of touch the team is with the current state of affairs.

https://medium.com/@localvoid/how-to-win-in-web-framework-benchmarks-8bc31af76ce7

was written before we split thr keyed and non-keyed impls into separate tables. the benchmarks are not "notoriously easy to fool" as they use mutation observers to validate that each framework does the necessary dom mutations in both cases, not just validates the output.

there are plenty of authors in that thread who know this has been the case for almost a year, yet no one says anything.

if you have components that make chains of network requests and run generally shitty code, of course a vdom diffing optimization isnt gonna make a blip on that radar.

**Comment by luwes** [comment]
Thanks for the feedback! Great to get more insight on this topic.

Startup time is really important for our use case, we're in search of a new rendering library for the Vimeo video player. Right now it uses 1) `innerHTML` (https://github.com/ccampbell/aftershave) and 2) direct DOM manipulation over time.

And this declarative approach is really appealing but library size and application size due to library must be minimal.

**Comment by vinyll** [comment]
I join and thank for the lib!
I fully rewrote the v1 of [Lego webcomponents](https://github.com/Polight/lego) with _petit-dom_ and it's been very smooth and pleasant.

The only glitch I could meet is that I must `render` with a single node.
I [applied the 'create a parent node' workaround](https://github.com/Polight/lego/blob/v1/lib/Component.js#L72) but it has consequences when applying CSS selectors.

Is there a way to actually render a list of nodes on the parentDomNode?

**Comment by vinyll** [comment]
> But I'm thinking of adding this eventually.

Is it still in your scope @yelouafi?

**Comment by yisar** [comment]
@yelouafi @vinyll 

> Is there a way to actually render a list of nodes on the parentDomNode?

https://github.com/yisar/fre/blob/next/src/reconciler.ts#L89

I want to add this to fre, how about using DocumentFragment?

https://developer.mozilla.org/zh-CN/docs/Web/API/DocumentFragment

Place a documentfragment as the root element for component, which is the same as you give `h('div')`

I don't know why almost all frameworks don't use document fragment. Why?

**Comment by yelouafi** [comment]
Fragments are supported in v0.4.1

**Comment by vinyll** [comment]
I'll upgrade [Lego](github.com/polight/lego) shortly, that will be a great upgrade! 👯

**Comment by yelouafi** [comment]
v0.5.0 adds the missing Fragment to jsx-runtime.
