### ISSUE TITLE
patch fails when root element changes

### ISSUE THREAD

**Issue by zaceno** [yelouafi/petit-dom#11]
Hi again! Noticed something unexpected while playing with petit-dom and reduced it to this example:

https://codepen.io/zaceno/pen/qYEQPw?editors=0011 Basically, if the top element is different in two vnodes `A` and `B`, then `patch(A, B)`  will do nothing. 

I did notice patch *returns* the new, appropriate element, making it possible for me to swap the old one out for the new one myself.  So I'm guessing this is intended behavior, but I didn't see anything about it in the README, and it caught me off guard.

Again, no problem to handle myself, but since it *is* so easy for a user to handle, perhaps this is something petit-dom could take care of internally? (I could PR it I think, if you're interested)
 
PS: I double checked in Chrome also this time, before filing an issue 😅

**Comment by yelouafi** [comment]
the lib already handles this; if you pass the parent element to patch it will take care of replacing. See

https://github.com/yelouafi/petit-dom/blob/5412b18ad26108762ebf5624ac1c5bd70c578e57/src/vdom.js#L224-L226

But you're right this should be documented

**Comment by zaceno** [comment]
Oh, nice! Good to know!

Thanks!
