### ISSUE TITLE
Is there an equivalent of dangerouslySetInnerHTML?

### ISSUE THREAD

**Issue by TomasHubelbauer** [yelouafi/petit-dom#13]
I have an API which returns HTML fragments. Is it possible to place them in raw in PetitDOM?

**Comment by yelouafi** [comment]
No but should be added. it can be done by adding the `innerHTML` prop to this list

https://github.com/yelouafi/petit-dom/blob/5412b18ad26108762ebf5624ac1c5bd70c578e57/src/vdom.js#L4

**Comment by TomasHubelbauer** [comment]
I ended up setting `innerHTML` after patching the DOM, but this sounds like a better way. Thanks for the info.

**Comment by yelouafi** [comment]
should be fixed in [v 0.2.0](https://github.com/yelouafi/petit-dom/releases/tag/v0.2.0)
