### ISSUE TITLE
Link doesn't render - Bug

### ISSUE THREAD

**Issue by cjh9** [yelouafi/petit-dom#15]
Look at this example:
```
<!doctype html>
<html lang="en">
<head>
  <title>petit-dom Link Bug</title>
</head>
<body>

  <script src="../../dist/petit-dom.dev.js"></script>
  <script>
    const {h, mount} = petitDom

    const vnode = h('div', null, [h('a', {href:'www.example.com'}, ['link'])]);

    document.body.appendChild(mount(vnode));
  </script>
</body>

</html>
```

The link won't render on the latest Chrome 66. When I edit the element in the inspector it says `<a xlink:href="www.example.com">link</a>` The `xlink` is creating the error, it works when I remove the   `href: XLINK_NS` in the `vdom.js`.

**Comment by yelouafi** [comment]
fixed in v0.2.2
