### ISSUE TITLE
Allow conditional rendering

### ISSUE THREAD

**Issue by cjh9** [yelouafi/petit-dom#21]
It is very handy to be able to conditional rendering, like

```js
isOpen && Component()
list.length && list.length.toString()
```

It is not possible right now. This is how I solved it in `h.js`. Should we add this to the library?

```js
function noNode(arg){
  return arg === null || arg === false || arg === undefined || arg === 0
}
 export function maybeFlatten(arr, isSVG) {
  for (var i = 0; i < arr.length; i++) {
    var ch = arr[i];
    if (isArray(ch)) {
      return flattenChildren(arr, i, arr.slice(0, i), isSVG);
    } else if (!isVNode(ch)) {
      arr[i] = { _text: ch == null ? "" : ch };
      arr[i] = { _text: noNode(ch) ? "" : ch };
    } else if (isSVG && !ch.isSVG) {
      ch.isSVG = true;
    }
```

**Comment by vinyll** [comment]
Conditional rendering is actually possible with PetitDom.
[Lego](https://github.com/Polight/lego) is based on [Brick](https://github.com/Polight/brick) that intensively uses PetitDom and I use conditions everyday with it.

Here's a [basic example](https://github.com/Polight/brick/blob/master/demo/index.html#L79) and [many examples in real life](https://professionals.tci.anthropedia.org/dist/x-app.js) where using conditions.

**Comment by yelouafi** [comment]
conditional rendering can be used with JS conditional expressions: `isOpen ? Component() : null`
