### ISSUE TITLE
Null doesn't remove previous node

### ISSUE THREAD

**Issue by cjh9** [yelouafi/petit-dom#31]
Consider this runnable example:

``` js
<body>
<div id="root"></div>
<script type="module">
    
import {h, patch, mount} from 'https://unpkg.com/petit-dom?module'

var oldVnode = h('div', {}, ['Hello there!'])
var newVnode = h('div', {}, [null])

var mounted = mount(oldVnode)
var root = document.getElementById('root')
root.appendChild(mounted)

patch(newVnode, oldVnode, mounted)

</script>
</body>
```
# Output

``` html
<div id="root"><div>Hello there!</div></div>
```

Shouldn't this remove the textnode? So you can do `isSomething ? Vdom() : null`

**Comment by yelouafi** [comment]
It works if used on nested nodes. In top level nodes you'rather use render. patch returns the new dom node so if nodes are different like in the case above you should replace the old one manually.

**Comment by cjh9** [comment]
> It works if used on nested nodes.

So you mean something like this?
``` js
var oldVnode = h('div', {}, [
    h('div', {}, [
        h('span',{}, ['Hello there!'])
    ])
])
var newVnode = h('div', {}, [
    h('div', {}, [
        h('span',{}, [null])
    ])
])
```
It still renders 'Hello there' after the patch...

**Comment by yelouafi** [comment]
Ooops! that was a stupid mistake
https://github.com/yelouafi/petit-dom/blob/46ea27b6477d47f471b55a55e880dec8ea3b76b9/src/vdom.js#L65

should be fixed by https://github.com/yelouafi/petit-dom/releases/tag/v0.3.3
