### ISSUE TITLE
Changing VNode type at root fails

### ISSUE THREAD

**Issue by j-sen** [yelouafi/petit-dom#32]
Changing type of VNode at root fails.
Version: 0.3.3

`
import { h, render } from "petit-dom";

const parentElement = document.getElementById("app");

render(h("h1", null, "Hello"), parentElement);
render(h("h2", null, "Hello"), parentElement);
`

The code above makes the browser complain 

> TypeError: Cannot read property 'childNodes' of undefined

Here is a link to sandbox for reproducing: https://codesandbox.io/s/confident-knuth-o41be

**Comment by yelouafi** [comment]
should be fixed in v0.3.4
