### ISSUE TITLE
Documentation for shouldUpdate

### ISSUE THREAD

**Issue by cjh9** [yelouafi/petit-dom#8]
Hi!
I'm trying to use petit-dom with render functions, and I would like to be able to control if the algorithm should stop patching at a particular position in the vdom tree. What do you mean with "You can also attach a `shouldUpdate` function to the render function"?

 I saw in the source that the `type` could either be a function or a string. I'm using the api right now like this:

  ```
var ButtonComponent = () => 
petit.h('button',{
   onclick:function(){},
   style: 'background:green' 
}, ['button'])
```

And then using the button somewhere
`h('div', {}, [ButtonComponent()]`

How should I tell a component to ignore parts of the dom, for example that have been modified externally?

**Comment by yelouafi** [comment]
You can do something like `ButtonComponent.shouldUpdate = (newProps, oldProps, newContent, oldContent) => { ... }` and return true or false to indicate if the patch process should go or ignore the current node
