### ISSUE TITLE
Handle input type="range"

### ISSUE THREAD

**Issue by cjh9** [yelouafi/petit-dom#9]
Hi again, sorry to spam you :)

I'm trying to get input type="range" to work, but I believe it triggers the `updateInput()` on line 52 in `vdom.js`. The `setProps()` function is called on line 61 with `null` as `oldProps`, so all the `min`, and `max` attribute will always be updated even if they need not to...

**Comment by yelouafi** [comment]
Sorry for the delay. I pushed a new release which should fix this.
